# Site settings
title: JLab
email: 12190586@inha.edu
description: >- 
  Inha University. 
  Naval Arcitechure & Ocean Engineering
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  Jaeyoon12190586
youtube_username: 

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

#header
header_pages:
  - /index/
  - /about/
  - /contact/


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
