# Configurations
title: JLab

author: Jaeyoon
email: 12190586@inha.edu
description: >

version: 1.0

url: "https://Jaeyoon12190586.github.io"
baseurl: "/Jaeyoon" 

github_username:  Jaeyoon12190586

# Build settings
markdown: kramdown
theme: minma
